---
title: "Tecnicas de Inferencia"
author: "Carlos Grande Nuñez, Veronica Gomez Gomez y Pablo Olmos Martinez,"
date: "10/20/2019"
output: 
  html_document:
    toc: true
    toc_float: true
    theme: united
---

# ANALISIS DE TECNICAS DE INFERENCIA.

El objetivo de esta practica es analizar las distintas tecnicas de inferencia usadas en clase. Para esta practica hemos usado el siguiente dataset:

https://www.kaggle.com/mishra5001/credit-card

Las librerias usadas son las siguientes:

- sampling
- normtest
- nortest

```{r setup, include=FALSE}
library(sampling)
library(normtest)
library(nortest) 

relPath <- getwd()
setwd(relPath)
unzip("credit-card.zip")
base <- read.csv (file="./credit-card/application_data.csv")
names (base)
summary (base)
```

## Muestreo del conjunto de datos

## Caracteristicas interesantes sujetas a estudio

## Estimaciones puntuales de las caracteristicas

## Intervalo de hipotesis para una de las caracteristicas

## Intervalo de confianza para la comparacion de dicha caracteristica

## Contrastes de hipotesis de independencia de las muestras

## Contraste de hipotesis para la caracteristica de estudio de una de las muestras

## Contraste de hipotesis de normalidad para una de las muestras

## Contraste de hipotesis para la comparacion de las muestras