version: "3"
services:

  pythonScript:
    image: akinorev/scriptpythonbook:latest
    volumes:
      - shared_volume:/usr/src/app/output
  apacheServer:
    image: httpd:latest
    volumes:
      - shared_volume:/usr/local/apache2/htdocs/

  whale:
    image: docker/whalesay
    command: ["cowsay", "release Compose!"]

  lb:
    image: dockercloud/haproxy
    links:
     - apacheServer
    ports:
     - '80:80'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  shared_volume:
