version: "3"
services:

  pythonScript:
    volumes:
      - shared_volume:/usr/src/app/output
    command: cat /usr/src/app/output

  apacheServer:
    volumes:
      - shared_volume:/usr/local/apache2/htdocs/

  lb:
    links:
     - apacheServer
    ports:
     - '80:80'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  whale:
    command: ["cowsay", "development Compose!"]

volumes:
  shared_volume:
